### ISSUE TITLE
Why not output to syslog?

### ISSUE THREAD

**Issue by fflorent** [YunoHost-Apps/nodered_ynh#49]
The log are currently written in the `/var/log/nodered/nodered.log` log file.

I wonder if that wouldn't be more convenient to output logs to syslog so we can check everything using the `journalctl` command. What do you think?

**Comment by tituspijean** [comment]
I merely applied [the standard from example_ynh](https://github.com/YunoHost/example_ynh/blob/master/conf/systemd.service#L11-L12), and the log can be seen from the webadmin thanks to https://github.com/YunoHost-Apps/nodered_ynh/blob/2ac2d60d0236d02221cb17e50f96df098e2a07cd/scripts/install#L144.

![image](https://user-images.githubusercontent.com/8769166/147412649-4291262e-2710-44af-87f2-56fd94a17247.png)

But I think you are right, since the journalctl is displayed in the webadmin too. 😅
